### PR TITLE
Add get_registered_devices method to Mobileclient [#315]

### PR DESCRIPTION
**Pull request by thebigmunch**

### CODE REVIEW

**Comment by thebigmunch** [comment]
Lulz, one of the docstring lines too long (damn iOS). Also, there seem to be a bunch of unrelated flake8 errors elsewhere that may need to be addressed at some point : P

**Comment by simon-weber** [comment]
yeah, I'm not sure when those got introduced. . .I may have either upgraded flake8 or changed the config and forgotten about it.

**Comment by simon-weber** [comment]
looks great; thanks!

**Comment by simon-weber** [comment]
fixed the linting errors in 90a02941b5093df8979469710a14bbd1fc12f8f2. I couldn't get my local flake8 installation to show them, though.

**Pull request merged**
